addr_operating_mode: 11
addr_pwm_limit: 36
addr_current_limit: 38
addr_torque_enable: 64
addr_led: 65
addr_hardware_error_status: 70
addr_vel_i_gain: 76
addr_vel_p_gain: 78
addr_pos_d_gain: 80
addr_pos_i_gain: 82
addr_pos_p_gain: 84
addr_goal_pwm: 100
addr_goal_current: 102
addr_goal_vel: 104
addr_profile_accel: 108
addr_profile_velocity: 112
addr_goal_position: 116
addr_moving: 122
addr_moving_status: 123
addr_present_pwm: 124
addr_present_current: 126
addr_present_velocity: 128
addr_present_position: 132
addr_indirect_start: 168

pos_length: 4
vel_length: 4
curr_length: 2
total_length: 10