initial_pos:
  index_dip_joint: 0.0
  index_mcp_joint: 0.0
  index_pip_abb_joint: 0.0
  index_pip_flex_joint: 0.0
  middle_dip_joint: 0.0
  middle_mcp_joint: 0.0
  middle_pip_abb_joint: 0.0
  middle_pip_flex_joint: 0.0
  ring_dip_joint: 0.0
  ring_mcp_joint: 0.0
  ring_pip_abb_joint: 0.0
  ring_pip_flex_joint: 0.0
  thumb_cmc_abb_joint: 0.0
  thumb_cmc_flex_joint: 0.0
  thumb_ip_joint: 0.0
  thumb_mcp_joint: 0.0
test_palm_sensor_pos:
  index_dip_joint: 0.0
  index_mcp_joint: 0.0
  index_pip_abb_joint: 0.0
  index_pip_flex_joint: 0.0
  middle_dip_joint: 0.0
  middle_mcp_joint: 0.0
  middle_pip_abb_joint: 0.0
  middle_pip_flex_joint: 0.0
  ring_dip_joint: 0.0
  ring_mcp_joint: 0.0
  ring_pip_abb_joint: 0.0
  ring_pip_flex_joint: 0.0
  thumb_cmc_abb_joint: 1.0532
  thumb_cmc_flex_joint: 1.4796
  thumb_mcp_joint: 2.0
  thumb_ip_joint: 1.2604
test_fingers_sensor_pos:
  index_dip_joint: -0.3491
  index_mcp_joint: 1.8032
  index_pip_abb_joint: 0
  index_pip_flex_joint: 1.9422
  middle_dip_joint: -0.3491
  middle_mcp_joint: 1.8032
  middle_pip_abb_joint: 0
  middle_pip_flex_joint: 1.9422
  ring_dip_joint: -0.3491
  ring_mcp_joint: 1.8032
  ring_pip_abb_joint: 0
  ring_pip_flex_joint: 1.9422
  thumb_cmc_abb_joint: 0.0
  thumb_cmc_flex_joint: 0.0
  thumb_ip_joint: 0.0
  thumb_mcp_joint: 0.0