# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  action_ns: follow_joint_trajectory
  controller_names:
    - index_controller
    - middle_controller
    - ring_controller
    - thumb_controller

  index_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - index_pip_flex_joint
      - index_pip_abb_joint
      - index_mcp_joint
      - index_dip_joint
  middle_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - middle_pip_flex_joint
      - middle_pip_abb_joint
      - middle_mcp_joint
      - middle_dip_joint
  ring_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - ring_pip_flex_joint
      - ring_pip_abb_joint
      - ring_mcp_joint
      - ring_dip_joint
  thumb_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - thumb_cmc_abb_joint
      - thumb_cmc_flex_joint
      - thumb_mcp_joint
      - thumb_ip_joint